# Generated by Django 2.1 on 2018-08-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MeterUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=16)),
                ('tariff', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='consumptionentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.MeterUser'),
        ),
    ]
