# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteruser',
            name='cache_avg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meteruser',
            name='cache_max',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
