# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_auto_20180821_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteruser',
            name='cache_avg',
        ),
        migrations.RemoveField(
            model_name='meteruser',
            name='cache_max',
        ),
    ]
